/// @author Ivano Bilenchi

#ifndef COWL_HASH_UTILS_H
#define COWL_HASH_UTILS_H

#include "cowl_std.h"

#define COWL_HASH_MULT 31

#define COWL_HASH_INIT_IRI 3
#define COWL_HASH_INIT_CLASS 5
#define COWL_HASH_INIT_OBJ_COMPL 7
#define COWL_HASH_INIT_NARY_BOOL 11
#define COWL_HASH_INIT_OBJ_QUANT 13
#define COWL_HASH_INIT_OBJ_CARD 17

#define COWL_HASH_INIT_OBJ_PROP 127
#define COWL_HASH_INIT_INV_OBJ_PROP 131

#define COWL_HASH_INIT_NAMED_INDIVIDUAL 151
#define COWL_HASH_INIT_ANON_INDIVIDUAL 157

#define COWL_HASH_INIT_DECL_AXIOM 179
#define COWL_HASH_INIT_SUBCLASS_AXIOM 181
#define COWL_HASH_INIT_EQ_CLS_AXIOM 191
#define COWL_HASH_INIT_DISJ_CLS_AXIOM 193
#define COWL_HASH_INIT_DISJ_UNION_AXIOM 197

#define COWL_HASH_INIT_SUB_OBJ_PROP_AXIOM 199
#define COWL_HASH_INIT_EQ_OBJ_PROP_AXIOM 211
#define COWL_HASH_INIT_DISJ_OBJ_PROP_AXIOM 223
#define COWL_HASH_INIT_INV_OBJ_PROP_AXIOM 227
#define COWL_HASH_INIT_OBJ_PROP_DOMAIN_AXIOM 229
#define COWL_HASH_INIT_OBJ_PROP_RANGE_AXIOM 233
#define COWL_HASH_INIT_FUNC_OBJ_PROP_AXIOM 239
#define COWL_HASH_INIT_INV_FUNC_OBJ_PROP_AXIOM 241
#define COWL_HASH_INIT_REFL_OBJ_PROP_AXIOM 251
#define COWL_HASH_INIT_IRREFL_OBJ_PROP_AXIOM 257
#define COWL_HASH_INIT_SYMM_OBJ_PROP_AXIOM 263
#define COWL_HASH_INIT_ASYMM_OBJ_PROP_AXIOM 269
#define COWL_HASH_INIT_TRANS_OBJ_PROP_AXIOM 271

#define COWL_HASH_INIT_CLS_ASSERT_AXIOM 277
#define COWL_HASH_INIT_SAME_IND_AXIOM 281
#define COWL_HASH_INIT_DIFF_IND_AXIOM 283
#define COWL_HASH_INIT_OBJ_PROP_ASSERT_AXIOM 293
#define COWL_HASH_INIT_NEG_OBJ_PROP_ASSERT_AXIOM 307
#define COWL_HASH_INIT_DATA_PROP_ASSERT_AXIOM 311
#define COWL_HASH_INIT_NEG_DATA_PROP_ASSERT_AXIOM 313

#define COWL_HASH_INIT_ONTO_ID 997

#define cowl_hash_iter(hash_acc, hash_new) ((hash_acc) * COWL_HASH_MULT + (hash_new))

#define cowl_hash_1(init, a) (cowl_hash_iter(init, a))
#define cowl_hash_2(init, a, b) (cowl_hash_iter(cowl_hash_iter(init, a), b))
#define cowl_hash_3(init, a, b, c) (cowl_hash_iter(cowl_hash_iter(cowl_hash_iter(init, a), b), c))
#define cowl_hash_4(init, a, b, c, d) \
    (cowl_hash_iter(cowl_hash_iter(cowl_hash_iter(cowl_hash_iter(init, a), b), c), d))

#endif // COWL_HASH_UTILS_H
