/**
 * @author Valerio Di Ceglie
 *
 * @copyright Copyright (c) 2024 SisInf Lab, Polytechnic University of Bari
 * @copyright <http://swot.sisinflab.poliba.it>
 * @copyright SPDX-License-Identifier: EPL-2.0
 *
 * @file
 */

#ifndef COWL_PRT_CONSTANTS_H
#define COWL_PRT_CONSTANTS_H

#include "cowl_axiom_type.h"  // IWYU pragma: keep
#include "cowl_entity_type.h" // IWYU pragma: keep

typedef enum CowlPRTLiteralType {
    COWL_OLT_STRING_LITERAL = 0,
    COWL_OLT_STRING_LITERAL_LANGUAGE,
    COWL_OLT_TYPED_LITERAL
} CowlPRTLiteralType;

#define COWL_PRT_FORMAT_VERSION 1U

#define COWL_PRT_FRAME_TYPE_SIZE 6U
#define COWL_PRT_FRAME_TYPE_BITMASK ((1U << COWL_PRT_FRAME_TYPE_SIZE) - 1U)

#define COWL_PRT_AXIOM_TYPE_COUNT (COWL_AT_COUNT + COWL_ET_COUNT - 1)
#define COWL_PRT_PREFIX_DECLS_FRAME COWL_PRT_AXIOM_TYPE_COUNT
#define COWL_PRT_ID_DECLS_FRAME (COWL_PRT_AXIOM_TYPE_COUNT + 1)
#define COWL_PRT_IRI_VERSION_FRAME (COWL_PRT_AXIOM_TYPE_COUNT + 2)
#define COWL_PRT_IMPORTS_FRAME (COWL_PRT_AXIOM_TYPE_COUNT + 3)
#define COWL_PRT_ANNOTATIONS_FRAME (COWL_PRT_AXIOM_TYPE_COUNT + 4)
#define COWL_PRT_RESET_FRAME (COWL_PRT_AXIOM_TYPE_COUNT + 5)

#define COWL_PRT_RESET_IDS_OFFSET 6U
#define COWL_PRT_RESET_IDS_BITMASK (1U << COWL_PRT_RESET_IDS_OFFSET)
#define COWL_PRT_RESET_PREFIXES_OFFSET 7U
#define COWL_PRT_RESET_PREFIXES_BITMASK (1U << COWL_PRT_RESET_PREFIXES_OFFSET)

#define COWL_PRT_PREFIX_DECL_IS_PREFIX_OFFSET 6U
#define COWL_PRT_PREFIX_DECL_IS_PREFIX_BITMASK (1U << COWL_PRT_PREFIX_DECL_IS_PREFIX_OFFSET)
#define COWL_PRT_ID_DECL_IS_IRI_OFFSET 6U
#define COWL_PRT_ID_DECL_IS_IRI_BITMASK (1U << COWL_PRT_ID_DECL_IS_IRI_OFFSET)

#define COWL_PRT_VERSION_OFFSET 7U
#define COWL_PRT_VERSION_BITMASK (1U << COWL_PRT_VERSION_OFFSET)

#define COWL_PRT_AXIOM_TYPE_SIZE 6U
#define COWL_PRT_AXIOM_ANNOT_OFFSET COWL_PRT_AXIOM_TYPE_SIZE
#define COWL_PRT_AXIOM_UTLITY_OFFSET (COWL_PRT_AXIOM_ANNOT_OFFSET + 1U)
#define COWL_PRT_AXIOM_TYPE_BITMASK ((1U << COWL_PRT_AXIOM_TYPE_SIZE) - 1U)
#define COWL_PRT_AXIOM_ANNOT_BITMASK (1U << COWL_PRT_AXIOM_ANNOT_OFFSET)
#define COWL_PRT_AXIOM_UTILITY_BITMASK (1U << COWL_PRT_AXIOM_UTLITY_OFFSET)

#endif // COWL_PRT_CONSTANTS_H
