/**
 * @author Valerio Di Ceglie
 *
 * @copyright Copyright (c) 2024 SisInf Lab, Polytechnic University of Bari
 * @copyright <http://swot.sisinflab.poliba.it>
 * @copyright SPDX-License-Identifier: EPL-2.0
 *
 * @file
 */

#ifndef COWL_PRT_CONSTANTS_H
#define COWL_PRT_CONSTANTS_H

#include "cowl_axiom_type.h"  // IWYU pragma: keep
#include "cowl_entity_type.h" // IWYU pragma: keep

typedef enum CowlPRTLiteralType {
    COWL_OLT_STRING_LITERAL = 0,
    COWL_OLT_STRING_LITERAL_LANGUAGE = 1,
    COWL_OLT_TYPED_LITERAL = 2,
} CowlPRTLiteralType;

typedef enum CowlPRTLiteralValueFormat {
    COWL_LVF_STRING = 0,
    COWL_LVF_COMP_STRING = 1,
    COWL_LVF_BOOL = 2,
    COWL_LVF_INT = 3,
    COWL_LVF_UINT = 4,
    COWL_LVF_FIXED_POINT = 5,
    COWL_LVF_E_NOTATION = 6,
} CowlPRTLiteralValueFormat;

typedef enum CowlPRTLiteralBool {
    COWL_LB_FALSE = 0,
    COWL_LB_TRUE = 1,
} CowlPRTLiteralBool;

enum {
    COWL_PRT_FORMAT_VERSION = 1U,

    COWL_PRT_FRAME_TYPE_SIZE = 6U,
    COWL_PRT_FRAME_TYPE_BITMASK = (1U << COWL_PRT_FRAME_TYPE_SIZE) - 1U,

    COWL_PRT_ADD_FRAME = 0,
    COWL_PRT_REMOVE_FRAME = 1,
    COWL_PRT_RESET_FRAME = 2,
    COWL_PRT_END_FRAME = 3,
    COWL_PRT_NS_DECLS_FRAME = 4,
    COWL_PRT_ID_DECLS_FRAME = 5,
    COWL_PRT_IRI_VERSION_FRAME = 6,
    COWL_PRT_IMPORTS_FRAME = 7,
    COWL_PRT_ANNOTATIONS_FRAME = 8,
    COWL_PRT_FIRST_AXIOM_FRAME = 9,

    COWL_PRT_RESET_NS_OFFSET = 6U,
    COWL_PRT_RESET_NS_BITMASK = 1U << COWL_PRT_RESET_NS_OFFSET,
    COWL_PRT_RESET_ID_OFFSET = 7U,
    COWL_PRT_RESET_ID_BITMASK = 1U << COWL_PRT_RESET_ID_OFFSET,

    COWL_PRT_NS_DECL_IS_PREFIX_OFFSET = 6U,
    COWL_PRT_NS_DECL_IS_PREFIX_BITMASK = 1U << COWL_PRT_NS_DECL_IS_PREFIX_OFFSET,
    COWL_PRT_ID_DECL_IS_IRI_OFFSET = 6U,
    COWL_PRT_ID_DECL_IS_IRI_BITMASK = 1U << COWL_PRT_ID_DECL_IS_IRI_OFFSET,

    COWL_PRT_VALUE_FORMAT_OFFSET = 2U,
    COWL_PRT_VALUE_FORMAT_SIZE = 6U,
    COWL_PRT_LITERAL_TYPE_BITMASK = (1U << COWL_PRT_VALUE_FORMAT_OFFSET) - 1U,
    COWL_PRT_VALUE_FORMAT_BITMASK = (1U << COWL_PRT_VALUE_FORMAT_SIZE) - 1U,

    COWL_PRT_VERSION_OFFSET = 7U,
    COWL_PRT_VERSION_BITMASK = 1U << COWL_PRT_VERSION_OFFSET,

    COWL_PRT_AXIOM_TYPE_SIZE = 6U,
    COWL_PRT_AXIOM_ANNOT_OFFSET = COWL_PRT_AXIOM_TYPE_SIZE,
    COWL_PRT_AXIOM_UTLITY_OFFSET = COWL_PRT_AXIOM_ANNOT_OFFSET + 1U,
    COWL_PRT_AXIOM_TYPE_BITMASK = (1U << COWL_PRT_AXIOM_TYPE_SIZE) - 1U,
    COWL_PRT_AXIOM_ANNOT_BITMASK = 1U << COWL_PRT_AXIOM_ANNOT_OFFSET,
    COWL_PRT_AXIOM_UTILITY_BITMASK = 1U << COWL_PRT_AXIOM_UTLITY_OFFSET,
};

#define COWL_PRT_BOOL_FALSE "false"
#define COWL_PRT_BOOL_TRUE "true"
#define COWL_PRT_BOOL_ZERO "0"
#define COWL_PRT_BOOL_ONE "1"

#endif // COWL_PRT_CONSTANTS_H
