/// @author Ivano Bilenchi

#ifndef COWL_OBJ_PROP_CHAR_AXIOM_TYPE_H
#define COWL_OBJ_PROP_CHAR_AXIOM_TYPE_H

#include "cowl_std.h"

COWL_BEGIN_DECLS

typedef enum CowlObjPropCharAxiomType {
    COPCAT_FUNCTIONAL,
    COPCAT_INVERSE_FUNCTIONAL,
    COPCAT_SYMMETRIC,
    COPCAT_ASYMMETRIC,
    COPCAT_TRANSITIVE,
    COPCAT_REFLEXIVE,
    COPCAT_IRREFLEXIVE
} CowlObjPropCharAxiomType;

COWL_END_DECLS

#endif // COWL_OBJ_PROP_CHAR_AXIOM_TYPE_H
